root = "."
tmp_dir = "tmp"

[build]
  cmd = "go run ./cmd/plugin-sync && go build -o ./tmp/foundry ./cmd/foundry"
  bin = "./tmp/foundry"
  full_bin = "./tmp/foundry serve-preview"
  include_ext = ["go", "yaml", "yml"]
  exclude_dir = ["tmp", "bin", "public", "vendor", ".git"]
  exclude_file = []
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = false
  log = "air-build-errors.log"
  delay = 300
  stop_on_error = true
  send_interrupt = true
  kill_delay = 500

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[log]
  time = true

[misc]
  clean_on_exit = true