package main

import (
	"bytes"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

const (
	configPath = "content/config/site.yaml"
	pluginsDir = "plugins"
	outputPath = "internal/generated/plugins_gen.go"
	modulePath = "github.com/sphireinc/foundry"
)

type siteConfig struct {
	Plugins struct {
		Enabled []string `yaml:"enabled"`
	} `yaml:"plugins"`
}

func main() {
	cfg, err := loadConfig(configPath)
	if err != nil {
		fatal("load config", err)
	}

	enabled := uniqueSorted(cfg.Plugins.Enabled)

	for _, name := range enabled {
		if err := validatePlugin(name); err != nil {
			fatal("validate plugin "+name, err)
		}
	}

	if err := os.MkdirAll(filepath.Dir(outputPath), 0o755); err != nil {
		fatal("create output dir", err)
	}

	content := generateFile(enabled)

	// Only write when the generated content actually changes, otherwise air freaks out and goes ito an infinite loop
	existing, err := os.ReadFile(outputPath)
	if err == nil && bytes.Equal(existing, []byte(content)) {
		return
	}
	if err != nil && !os.IsNotExist(err) {
		fatal("read existing generated imports", err)
	}

	if err := os.WriteFile(outputPath, []byte(content), 0o644); err != nil {
		fatal("write generated imports", err)
	}
}

func loadConfig(path string) (*siteConfig, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}

	var cfg siteConfig
	if err := yaml.Unmarshal(b, &cfg); err != nil {
		return nil, err
	}

	return &cfg, nil
}

func validatePlugin(name string) error {
	if strings.TrimSpace(name) == "" {
		return fmt.Errorf("plugin name cannot be empty")
	}
	if strings.Contains(name, "/") || strings.Contains(name, `\`) {
		return fmt.Errorf("plugin name %q must be a single directory name", name)
	}

	root := filepath.Join(pluginsDir, name)
	info, err := os.Stat(root)
	if err != nil {
		if os.IsNotExist(err) {
			return fmt.Errorf("plugin %q is enabled but directory %q does not exist", name, root)
		}
		return err
	}
	if !info.IsDir() {
		return fmt.Errorf("plugin path %q is not a directory", root)
	}

	foundGo := false
	err = filepath.WalkDir(root, func(path string, d fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if d.IsDir() {
			return nil
		}
		if filepath.Ext(path) == ".go" {
			foundGo = true
		}
		return nil
	})
	if err != nil {
		return err
	}

	if !foundGo {
		return fmt.Errorf("plugin %q has no .go files under %q", name, root)
	}

	return nil
}

func uniqueSorted(in []string) []string {
	set := make(map[string]struct{}, len(in))
	for _, v := range in {
		v = strings.TrimSpace(v)
		if v == "" {
			continue
		}
		set[v] = struct{}{}
	}

	out := make([]string, 0, len(set))
	for v := range set {
		out = append(out, v)
	}
	sort.Strings(out)
	return out
}

func generateFile(enabled []string) string {
	var buf bytes.Buffer

	buf.WriteString("// Code generated by cmd/plugin-sync; DO NOT EDIT.\n")
	buf.WriteString("package generated\n\n")

	if len(enabled) == 0 {
		return buf.String()
	}

	buf.WriteString("import (\n")
	for _, name := range enabled {
		fmt.Fprintf(&buf, "\t_ %q\n", modulePath+"/plugins/"+name)
	}
	buf.WriteString(")\n")

	return buf.String()
}

func fatal(prefix string, err error) {
	fmt.Fprintf(os.Stderr, "%s: %v\n", prefix, err)
	os.Exit(1)
}
