// docs-build renders the canonical Markdown guides into the GitHub Pages site.
package main

import (
	"bytes"
	"fmt"
	"html"
	"net/url"
	"os"
	"path"
	"path/filepath"
	"strings"

	"github.com/yuin/goldmark"
	"github.com/yuin/goldmark/ast"
	"github.com/yuin/goldmark/extension"
	"github.com/yuin/goldmark/parser"
	"github.com/yuin/goldmark/text"
)

var guides = []string{"editorial-workflows", "media-management", "site-search", "extension-authoring", "installation-updates", "content-bundles", "managed-runtime-boundary"}

func main() {
	if err := build(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func build() error {
	shell, err := os.ReadFile("docs/index.html")
	if err != nil {
		return err
	}
	headerStart := strings.Index(string(shell), "<header")
	headerEnd := strings.Index(string(shell), "</header>")
	if headerStart < 0 || headerEnd < 0 {
		return fmt.Errorf("docs/index.html has no shared header")
	}
	header := string(shell)[headerStart : headerEnd+len("</header>")]
	header = strings.ReplaceAll(header, `href="./`, `href="../`)
	header = strings.ReplaceAll(header, `src="./`, `src="../`)
	header = strings.ReplaceAll(header, ` aria-current="page"`, "")
	md := goldmark.New(goldmark.WithExtensions(extension.GFM), goldmark.WithParserOptions(parser.WithAutoHeadingID()))
	for _, guide := range guides {
		source, err := os.ReadFile(filepath.Join("docs", guide+".md")) // #nosec G304 -- Guide names come from the fixed catalog above.
		if err != nil {
			return err
		}
		title := strings.TrimSpace(strings.TrimPrefix(strings.SplitN(string(source), "\n", 2)[0], "# "))
		doc := md.Parser().Parse(text.NewReader(source))
		if err := ast.Walk(doc, func(node ast.Node, entering bool) (ast.WalkStatus, error) {
			if link, ok := node.(*ast.Link); ok && entering {
				link.Destination = []byte(siteLink(string(link.Destination)))
			}
			return ast.WalkContinue, nil
		}); err != nil {
			return err
		}
		var body bytes.Buffer
		if err := md.Renderer().Render(&body, source, doc); err != nil {
			return err
		}
		activeHeader := strings.ReplaceAll(header, `href="../`+guide+`/"`, `href="../`+guide+`/" aria-current="page"`)
		content := strings.ReplaceAll(body.String(), "<table>", `<div class="table-scroll"><table>`)
		content = strings.ReplaceAll(content, "</table>", "</table></div>")
		page := fmt.Sprintf(`<!doctype html>
<!-- Generated by go run ./scripts/cmd/docs-build; edit docs/%s.md. -->
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>%s · Foundry Documentation</title><script src="../theme-toggle.js"></script><link rel="stylesheet" href="../site.css"></head>
<body><div class="shell">%s<main class="content-card generated-guide"><div class="page-body">%s</div></main>
<footer class="footer"><span><a href="../%s.md">Markdown source</a> · <a href="../">Documentation home</a></span></footer></div></body></html>
`, guide, html.EscapeString(title), activeHeader, content, guide)
		dir := filepath.Join("docs", guide)
		if err := os.MkdirAll(dir, 0o755); err != nil { // #nosec G301 -- Public documentation must be readable by web servers.
			return err
		}
		if err := os.WriteFile(filepath.Join(dir, "index.html"), []byte(page), 0o644); err != nil { // #nosec G306 G703 -- Public HTML; output paths use only the fixed guide catalog.
			return err
		}
	}
	return nil
}

// Markdown sources live directly in docs/; rendered pages are one level deeper.
func siteLink(destination string) string {
	u, err := url.Parse(destination)
	if err != nil || u.IsAbs() || u.Host != "" || u.Path == "" || strings.HasPrefix(u.Path, "/") {
		return destination
	}
	target := path.Clean(path.Join("docs", u.Path))
	for _, guide := range guides {
		if target == "docs/"+guide+".md" {
			u.Path = "../" + guide + "/"
			return u.String()
		}
	}
	if strings.HasPrefix(target, "docs/") {
		u.Path = "../" + strings.TrimPrefix(target, "docs/")
		return u.String()
	}
	u.Path = "/sphireinc/Foundry/blob/main/" + target
	u.Scheme, u.Host = "https", "github.com"
	return u.String()
}
