package plugins

import (
	"bytes"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/sphireinc/foundry/internal/consts"
	"gopkg.in/yaml.v3"
)

const (
	DefaultSyncConfigPath = consts.ConfigFilePath
	DefaultSyncPluginsDir = "plugins"
	DefaultSyncOutputPath = "internal/generated/plugins_gen.go"
	DefaultSyncModulePath = "github.com/sphireinc/foundry"
)

type syncSiteConfig struct {
	Plugins struct {
		Enabled []string `yaml:"enabled"`
	} `yaml:"plugins"`
}

type SyncOptions struct {
	ConfigPath string
	PluginsDir string
	OutputPath string
	ModulePath string
}

func SyncFromConfig(opts SyncOptions) error {
	opts = normalizeSyncOptions(opts)

	cfg, err := loadSyncConfig(opts.ConfigPath)
	if err != nil {
		return fmt.Errorf("load config: %w", err)
	}

	return SyncEnabledPlugins(opts, cfg.Plugins.Enabled)
}

func SyncEnabledPlugins(opts SyncOptions, enabled []string) error {
	opts = normalizeSyncOptions(opts)

	enabled = uniqueSorted(enabled)
	inProcess := make([]string, 0, len(enabled))

	for _, name := range enabled {
		meta, err := validatePluginForSync(opts.PluginsDir, name)
		if err != nil {
			return fmt.Errorf("validate plugin %s: %w", name, err)
		}
		if !strings.EqualFold(strings.TrimSpace(meta.Runtime.Mode), "rpc") {
			inProcess = append(inProcess, name)
		}
	}

	if err := os.MkdirAll(filepath.Dir(opts.OutputPath), 0o755); err != nil {
		return fmt.Errorf("create output dir: %w", err)
	}

	content := generateImportsFile(opts.ModulePath, inProcess)

	existing, err := os.ReadFile(opts.OutputPath)
	if err == nil && bytes.Equal(existing, []byte(content)) {
		return nil
	}
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("read existing generated imports: %w", err)
	}

	if err := os.WriteFile(opts.OutputPath, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write generated imports: %w", err)
	}

	return nil
}

func normalizeSyncOptions(opts SyncOptions) SyncOptions {
	if strings.TrimSpace(opts.ConfigPath) == "" {
		opts.ConfigPath = DefaultSyncConfigPath
	}
	if strings.TrimSpace(opts.PluginsDir) == "" {
		opts.PluginsDir = DefaultSyncPluginsDir
	}
	if strings.TrimSpace(opts.OutputPath) == "" {
		opts.OutputPath = DefaultSyncOutputPath
	}
	if strings.TrimSpace(opts.ModulePath) == "" {
		opts.ModulePath = DefaultSyncModulePath
	}
	return opts
}

func loadSyncConfig(path string) (*syncSiteConfig, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}

	var cfg syncSiteConfig
	if err := yaml.Unmarshal(b, &cfg); err != nil {
		return nil, err
	}

	return &cfg, nil
}

func validatePluginForSync(pluginsDir, name string) (*Metadata, error) {
	var err error
	name, err = validatePluginName(name)
	if err != nil {
		return nil, err
	}

	root := filepath.Join(pluginsDir, name)
	info, err := os.Stat(root)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, fmt.Errorf("plugin %q is enabled but directory %q does not exist", name, root)
		}
		return nil, err
	}
	if !info.IsDir() {
		return nil, fmt.Errorf("plugin path %q is not a directory", root)
	}

	meta, err := LoadMetadata(pluginsDir, name)
	if err != nil {
		return nil, err
	}
	if strings.EqualFold(strings.TrimSpace(meta.Runtime.Mode), "rpc") {
		return &meta, EnsureRuntimeSupported(meta)
	}

	foundGo := false
	err = filepath.WalkDir(root, func(path string, d fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if d.IsDir() {
			return nil
		}
		if filepath.Ext(path) == ".go" {
			foundGo = true
		}
		return nil
	})
	if err != nil {
		return nil, err
	}

	if !foundGo {
		return nil, fmt.Errorf("plugin %q has no .go files under %q", name, root)
	}

	return &meta, nil
}

func uniqueSorted(in []string) []string {
	set := make(map[string]struct{}, len(in))
	for _, v := range in {
		v = strings.TrimSpace(v)
		if v == "" {
			continue
		}
		set[v] = struct{}{}
	}

	out := make([]string, 0, len(set))
	for v := range set {
		out = append(out, v)
	}
	sort.Strings(out)
	return out
}

func generateImportsFile(modulePath string, enabled []string) string {
	var buf bytes.Buffer

	buf.WriteString("// Code generated by plugin sync; DO NOT EDIT.\n")
	buf.WriteString("package generated\n\n")

	if len(enabled) == 0 {
		return buf.String()
	}

	buf.WriteString("import (\n")
	for _, name := range enabled {
		_, _ = fmt.Fprintf(&buf, "\t_ %q\n", strings.TrimRight(modulePath, "/")+"/plugins/"+name)
	}
	buf.WriteString(")\n")

	return buf.String()
}

func isValidRepoRef(v string) bool {
	v = strings.TrimSpace(v)
	if v == "" {
		return false
	}

	parts := strings.Split(v, "/")
	return len(parts) >= 3 && parts[0] != "" && parts[1] != "" && parts[2] != ""
}
