users:
    - username: admin
      name: Admin
      email: admin@example.com
      role: admin
      password_hash: argon2id$65536$3$2$enipjk85SldefbiLo4AAOA$O1Ie6YSGZ4dCxDqnFD6J5tS7BUy244QPUVD0RTIbPJQ
