environment: "development"
base_url: "http://localhost:8080"

server:
  addr: ":8080"
  live_reload: true
  auto_open_browser: false
  debug_routes: false

admin:
  local_only: false
  debug:
    pprof: true

backup:
  dir: "data/backups"
