package router

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/sphireinc/foundry/internal/config"
	"github.com/sphireinc/foundry/internal/content"
)

type Resolver struct {
	cfg *config.Config
}

func NewResolver(cfg *config.Config) *Resolver {
	return &Resolver{cfg: cfg}
}

func (r *Resolver) AssignURLs(graph *content.SiteGraph) error {
	if graph == nil {
		return fmt.Errorf("site graph is nil")
	}

	graph.ByURL = make(map[string]*content.Document, len(graph.Documents))

	for _, doc := range graph.Documents {
		if doc == nil {
			continue
		}

		url, err := r.URLForDocument(doc)
		if err != nil {
			return fmt.Errorf("assign url for %s: %w", doc.SourcePath, err)
		}

		doc.URL = url

		if existing, ok := graph.ByURL[url]; ok {
			return fmt.Errorf(
				"route collision: %q is generated by both %s and %s",
				url,
				existing.SourcePath,
				doc.SourcePath,
			)
		}

		graph.ByURL[url] = doc
	}

	return nil
}

func (r *Resolver) URLForDocument(doc *content.Document) (string, error) {
	if doc == nil {
		return "", fmt.Errorf("document is nil")
	}

	switch doc.Type {
	case "page":
		return r.pageURL(doc), nil
	case "post":
		return r.postURL(doc), nil
	default:
		return "", fmt.Errorf("unsupported document type %q", doc.Type)
	}
}

func (r *Resolver) pageURL(doc *content.Document) string {
	slug := strings.TrimSpace(doc.Slug)
	lang := strings.TrimSpace(doc.Lang)

	if slug == "" || slug == "index" {
		if lang == "" || lang == r.cfg.DefaultLang {
			return "/"
		}
		return "/" + lang + "/"
	}

	if lang == "" || lang == r.cfg.DefaultLang {
		return "/" + slug + "/"
	}

	return "/" + lang + "/" + slug + "/"
}

func (r *Resolver) postURL(doc *content.Document) string {
	slug := strings.TrimSpace(doc.Slug)
	lang := strings.TrimSpace(doc.Lang)

	if lang == "" || lang == r.cfg.DefaultLang {
		return "/posts/" + slug + "/"
	}

	return "/" + lang + "/posts/" + slug + "/"
}

func sourceToSlug(path string) string {
	base := filepath.Base(path)
	return strings.TrimSuffix(base, filepath.Ext(base))
}
